[build]
  base = "artifacts/peywend"
  command = "pnpm run build"
  publish = "build"

[build.environment]
  PORT = "3000"
  BASE_PATH = "/"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
